/// Generated by ChatGPT (OpenAI)
use psi::threaded::run_threaded;
use psi::types::Element;

use sha2::{Digest, Sha512};

fn make_element(v: u8) -> Element {
  let mut hasher = Sha512::new();
  hasher.update([v]);
  let result = hasher.finalize();

  let mut e = [0u8; 64];
  e.copy_from_slice(&result);
  e
}

fn contains_elem(set: &[Element], v: u8) -> bool {
  set.contains(&make_element(v))
}

#[test]
fn threaded_small_example() {
  let x = vec![make_element(1), make_element(2), make_element(3)];

  let y = vec![make_element(2), make_element(3), make_element(4)];

  let intersection = run_threaded(x, y);

  // Expected intersection: {2,3}
  assert_eq!(intersection.len(), 2);
  assert!(contains_elem(&intersection, 2));
  assert!(contains_elem(&intersection, 3));
}
